### ISSUE TITLE
Support multiple providers

### ISSUE THREAD

**Issue by giddie** [jjcarstens/ueberauth_okta#10]
It looks like only one global set of credentials for Okta can be used. However, Ueberauth allows multiple providers to be configured using the same strategy. So in the example given in the documentation:

```elixir
config :ueberauth, Ueberauth,
  providers: [
    okta: { Ueberauth.Strategy.Okta, [] }
  ]
```

The provider here is `:okta`, but another one could be defined using this strategy, and it could require different credentials. But the credentials are provided globally for the strategy, with no reference to the individual provider:

```elixir
config :ueberauth, Ueberauth.Strategy.Okta.OAuth,
  client_id: System.get_env("OKTA_CLIENT_ID"),
  client_secret: System.get_env("OKTA_CLIENT_SECRET"),
  site: "https://your-doman.okta.com"
```

**Comment by jjcarstens** [comment]
Thanks @giddie ! This is a fairly big oversight. I'll get a fix up shortly

**Comment by jjcarstens** [comment]
@giddie I have changes in #11 . Would you be able to test it with your setup? (I no longer am able to use Okta so can't test end-to-end myself)

I'm going to try and add some unit tests later, but am timed out for now

**Comment by giddie** [comment]
This seems to work much better. Thanks for the quick work. Just one small tweak was required to get the flow working for me:

https://github.com/jjcarstens/ueberauth_okta/pull/12
