### ISSUE TITLE
Docs for multi-tenant support?

### ISSUE THREAD

**Issue by petelacey** [jjcarstens/ueberauth_okta#9]
Last month you merged in PR #8, which is great. However, I cannot figure out to take advantage of it. I hate to ask, but would you be able to provide some documentation on how to use this strategy in a multi-tenant environment?

In other words, assume that the client_id, client_secret, and site are all stored in the database, one set for each of my Okta customers. How would I go about calling into this strategy with these?

If I use a controller with `plug Ueberauth`, then this strategy takes over and retrieves the default single-tenant configuration. If I use a controller with my own `request` and `callback` actions, I can call this strategy with `Ueberauth.run_request/3`, but I don't know how to process the callback after calling `Ueberauth.run_callback/3`. Or even if that's the right approach at all.

Any help you can offer would be appreciated? Thanks.

**Comment by jjcarstens** [comment]
@ryanzidago do you have any insight here?

I actually don't use Okta anymore, but try to maintain this as best I can keep up with the community. As such, I'm pretty behind on the direct course of action here.

I need to dig into Ueberauth a bit more to see what's going with their plug and I'm not entirely sure how quickly I'll find time to do that.

**Comment by petelacey** [comment]
FYI, I have managed to kludge together something that works. I would update the docs here myself, but it honestly is a kludge. I am going to close this issue. Thanks!

**Comment by edwardcashmere** [comment]
@petelacey Hey I am also stuck here try to process the when callback is called. How did you set up the callback in okta client_app to accept .  `/auth/okta/callback/#{key}` I tried using the wildcard `/auth/okta/callback/*` but its not working

**Comment by petelacey** [comment]
It's not pretty, but it works. This assumes that your users are initiating the request via Okta by clicking on a tile in their launcher, and that request goes to `/auth/okta`.

1. Setup a route like so:
```elixir
  scope "/auth", ExampleWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/:provider", SSOController, :request
    get "/:provider/callback", SSOController, :callback
  end
```

2. In your controller, pluck out the customer's domain via the "iss" component in the query string, and use that to retrieve their okta settings from your DB.
3. Next comes the kludge. Take the customer's domain (or some other unique identifier) and **put it in the session**.
4. Then run the Ueberauth request yourself.

```elixir
  def request(conn, %{"provider" => provider, "iss" => domain}) do
    [_, domain] = String.split(domain, "https://")
    customer = get_customer_from your_db(domain)
    conn
    |> put_session(:okta_tenant, customer.domain)
    |> Ueberauth.run_request(
         provider,
         {
           Ueberauth.Strategy.Okta,
           [
             client_id: customer.client_id,
             client_secret: customer.client_secret,
             site: "https://#{customer.issuer}"
           ]
         }
  end
```

5. Next, we're going to have two callbacks, one for exchanging the returned okta code for user info, and then a second, "normal," one that we will call once we have that user info. 
6. When Okta initiates the callback phase it does not :angry: supply the customer's domain. This is why we needed the cookie. So the first callback plucks the domain (or other ID) out of the session, then runs Ueberauth's okta strategy callback to exchange the okta-provided code for user info that we then pass into the real callback

```elixir
  def callback(%{assigns: %{ueberauth_failure: reason}} = conn, _params) do
      Logger.warning("some meaningful log message")
      conn
      |> put_flash(:alert, "Some meaningful user message")
      |> redirect(to: Routes.user_session_path(conn, :new))
  end

  # The second callback (must proceed first for pattern matching). Called with user data on success
  def callback(%{assigns: %{ueberauth_auth: %{info: _info} = auth_data}} = conn, _params) do
    raw_user = auth_data.extra.raw_info.user
    user = auth_data.info
    Logger.info("SSO succeeded. Raw: #{inspect(raw_user)}. Normalized: #{inspect(user)}")

    %{info: %{email: email}} = auth_data
    user  = get_user_from_your_db(email)

    # You'll likely have other requirements here for logging, user updates, and such, but at a minimum, this is
    # where you log the user into your app returning a `conn`, probably in the form of a redirect to your home page.
    UserAuth.log_in_user(conn, user, %{})
  end

  # First callback to exchange returned code for user info
  def callback(conn, %{"provider" => provider} = params) do
    domain = get_session(conn, :okta_tenant)
    if domain do
      customer = get_customer_from your_db(domain)

      Ueberauth.run_callback(
        conn,
        provider,
        {
         Ueberauth.Strategy.Okta,
          [
            client_id: customer.sso_client_id,
            client_secret: customer.sso_client_secret,
            site: "https://#{customer.sso_domain}"
          ]
        }
      ) |> callback(params)
    else
      Logger.warning("some meaningful log message")
      conn
      |> put_flash(:alert, "Some meaningful user message")
      |> redirect(to: Routes.user_session_path(conn, :new))
    end
```

Most of the code pasted above is derived from my actual code, but I may have made some typos while transposing it here. But this should get you going in the right direction.

**Comment by edwardcashmere** [comment]
if  initiating the request via Okta by clicking on a tile in their launcher. the `okta_tenant` is provided inside the session ?

**Comment by petelacey** [comment]
@edwardcashmere I'm not sure I understand your question. Basically, a user has to kick off the whole login flow by POSTing to `/auth/okta`. One way to do that is to simply have a "Login with Okta" button on your login page. However, most Okta users would prefer to use the [Okta dashboard](https://www.okta.com/okta-end-user-experience/).

If your customers add a tile to their dashboard that points at your app, then the URL sent to you will have an `iss` (issuer) component in its query string, like so: `https://yourapp.yourcompany.com/auth/okta/?iss=https://yourcustomer.okta.com`. 

The code in my previous reply parses the domain (`yourcustomer.okta.com`) out of that `iss` param and uses it to retrieve the customer's okta settings from the DB. It _also_  puts the domain *name* in a Phoenix session with the key `okta_tenant`. It does this because Okta (and all OIDC IdPs) will call us twice: the first time to kick off the login flow (if necessary) and again after the user has logged in to Okta. The problem is that the first time we have a reference to who the customer is via the `iss` param, but the second time we don't. Sticking the domain in the session, allows us to know who the caller is for the second request.

I hope that helps clarify things. And to be fair, the absence of the clearly needed `iss` param in the callback makes me wonder if I'm doing this all wrong, but a question I put on stackoverflow indicates I'm not: https://stackoverflow.com/questions/77434591/multi-tenant-oidc-okta-how-to-know-the-domain-site-when-exchanging-authorizat

**Comment by edwardcashmere** [comment]
@petelacey thank you so much . I got it working . definitely writing a blog about this
